### PR TITLE
Completed the Covid-19 Analysis Project

### PR DESCRIPTION
**Pull request by AadeshKabra**

### CODE REVIEW

**Comment by AKACHI-4** [comment]
@AadeshKabra Also add some documentation too in `notebook.ipnyb` so other can understand it as well..

**Comment by AKACHI-4** [comment]
Also link the dataset in your notebook which u are using ..

**Comment by AadeshKabra** [comment]
Now, I have added documentation in the notebook. Also the link for the dataset is mentioned in the notebook and present in the folder as well.

**Comment by AKACHI-4** [comment]
hey @AadeshKabra .. no need to commit the dataset file also change the name of your notebook with `notebook.ipnyb`

**Comment by AadeshKabra** [comment]
Did the changes

**Comment by AKACHI-4** [comment]
**Great work, @AadeshKabra !**

### Congratulations 🎉, your pull request has been successfully merged!

If you find this repository helpful, please consider giving us a star by clicking ⭐.

And don't forget to share your achievement with your friends and us in [Discussions]() ! 🚀

**Pull request merged**
