### PR TITLE
Completed the Social Data Usage analysis

### PR DESCRIPTION
**Pull request by AadeshKabra**
Completed the Social media usage analysis project. I have used a different and better dataset. Documentation is also added in the notebook. 
Dataset Link: https://www.kaggle.com/code/salmaneunus/social-media-analysis-dataset-extracting-cleaning/input
Dataset link is also mentioned in the notebook

### CODE REVIEW

**Comment by AKACHI-4** [comment]
Hey @AadeshKabra, there's no need to commit the datasets. keep only `notebook.ipynb` there. 

Also, after reviewing your notebook, I believe it would be beneficial to include some docs/notes within it so that other contributors can understand it as well.

**Comment by AKACHI-4** [comment]
Hey @AadeshKabra Kindly also add some docs to your notebook..

**Comment by AadeshKabra** [comment]
Now added the readme.md file which contains the documentation for the notebook. Also, some documentation is present in the notebook in the form of comments

**Comment by AKACHI-4** [comment]
Hey @AadeshKabra, great! One last change: there's no need to create a separate README.md, so please delete that and add Markdown notes directly in `notebook.ipynb`.

**Comment by AadeshKabra** [comment]
Hi, Made the suggested changes

**Comment by AKACHI-4** [comment]
Great work, @AadeshKabra  ! 👏

### Congratulations 🎉, your pull request has been successfully merged!

If you find this repository helpful, please consider giving us a star by clicking ⭐.

And don't forget to share your achievement with your friends and us in [Discussions](https://github.com/OpenCodeEra/ML-X/discussions) ! 🚀

**Pull request merged**
